//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDemo.WebAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebAPI.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SimpleDemo.WebAPI.HelloWorldResponse HelloWorld(SimpleDemo.WebAPI.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.HelloWorldResponse> HelloWorldAsync(SimpleDemo.WebAPI.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 jkxlh 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/init", ReplyAction="*")]
        SimpleDemo.WebAPI.initResponse init(SimpleDemo.WebAPI.initRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/init", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.initResponse> initAsync(SimpleDemo.WebAPI.initRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 jczbh 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/init1", ReplyAction="*")]
        SimpleDemo.WebAPI.init1Response init1(SimpleDemo.WebAPI.init1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/init1", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.init1Response> init1Async(SimpleDemo.WebAPI.init1Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 zdlx 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sqsq", ReplyAction="*")]
        SimpleDemo.WebAPI.sqsqResponse sqsq(SimpleDemo.WebAPI.sqsqRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sqsq", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.sqsqResponse> sqsqAsync(SimpleDemo.WebAPI.sqsqRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SimpleDemo.WebAPI.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SimpleDemo.WebAPI.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="init", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.initRequestBody Body;
        
        public initRequest() {
        }
        
        public initRequest(SimpleDemo.WebAPI.initRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class initRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jkxlh;
        
        public initRequestBody() {
        }
        
        public initRequestBody(string jkxlh) {
            this.jkxlh = jkxlh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class initResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="initResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.initResponseBody Body;
        
        public initResponse() {
        }
        
        public initResponse(SimpleDemo.WebAPI.initResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class initResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string initResult;
        
        public initResponseBody() {
        }
        
        public initResponseBody(string initResult) {
            this.initResult = initResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class init1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="init1", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.init1RequestBody Body;
        
        public init1Request() {
        }
        
        public init1Request(SimpleDemo.WebAPI.init1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class init1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jczbh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jcxdh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zdlx;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mac;
        
        public init1RequestBody() {
        }
        
        public init1RequestBody(string jczbh, string jcxdh, string zdlx, string ip, string mac) {
            this.jczbh = jczbh;
            this.jcxdh = jcxdh;
            this.zdlx = zdlx;
            this.ip = ip;
            this.mac = mac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class init1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="init1Response", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.init1ResponseBody Body;
        
        public init1Response() {
        }
        
        public init1Response(SimpleDemo.WebAPI.init1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class init1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string init1Result;
        
        public init1ResponseBody() {
        }
        
        public init1ResponseBody(string init1Result) {
            this.init1Result = init1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sqsqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sqsq", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.sqsqRequestBody Body;
        
        public sqsqRequest() {
        }
        
        public sqsqRequest(SimpleDemo.WebAPI.sqsqRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sqsqRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string zdlx;
        
        public sqsqRequestBody() {
        }
        
        public sqsqRequestBody(string zdlx) {
            this.zdlx = zdlx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sqsqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sqsqResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpleDemo.WebAPI.sqsqResponseBody Body;
        
        public sqsqResponse() {
        }
        
        public sqsqResponse(SimpleDemo.WebAPI.sqsqResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sqsqResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sqsqResult;
        
        public sqsqResponseBody() {
        }
        
        public sqsqResponseBody(string sqsqResult) {
            this.sqsqResult = sqsqResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : SimpleDemo.WebAPI.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SimpleDemo.WebAPI.Service1Soap>, SimpleDemo.WebAPI.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleDemo.WebAPI.HelloWorldResponse SimpleDemo.WebAPI.Service1Soap.HelloWorld(SimpleDemo.WebAPI.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SimpleDemo.WebAPI.HelloWorldRequest inValue = new SimpleDemo.WebAPI.HelloWorldRequest();
            inValue.Body = new SimpleDemo.WebAPI.HelloWorldRequestBody();
            SimpleDemo.WebAPI.HelloWorldResponse retVal = ((SimpleDemo.WebAPI.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.HelloWorldResponse> SimpleDemo.WebAPI.Service1Soap.HelloWorldAsync(SimpleDemo.WebAPI.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleDemo.WebAPI.HelloWorldResponse> HelloWorldAsync() {
            SimpleDemo.WebAPI.HelloWorldRequest inValue = new SimpleDemo.WebAPI.HelloWorldRequest();
            inValue.Body = new SimpleDemo.WebAPI.HelloWorldRequestBody();
            return ((SimpleDemo.WebAPI.Service1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleDemo.WebAPI.initResponse SimpleDemo.WebAPI.Service1Soap.init(SimpleDemo.WebAPI.initRequest request) {
            return base.Channel.init(request);
        }
        
        public string init(string jkxlh) {
            SimpleDemo.WebAPI.initRequest inValue = new SimpleDemo.WebAPI.initRequest();
            inValue.Body = new SimpleDemo.WebAPI.initRequestBody();
            inValue.Body.jkxlh = jkxlh;
            SimpleDemo.WebAPI.initResponse retVal = ((SimpleDemo.WebAPI.Service1Soap)(this)).init(inValue);
            return retVal.Body.initResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.initResponse> SimpleDemo.WebAPI.Service1Soap.initAsync(SimpleDemo.WebAPI.initRequest request) {
            return base.Channel.initAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleDemo.WebAPI.initResponse> initAsync(string jkxlh) {
            SimpleDemo.WebAPI.initRequest inValue = new SimpleDemo.WebAPI.initRequest();
            inValue.Body = new SimpleDemo.WebAPI.initRequestBody();
            inValue.Body.jkxlh = jkxlh;
            return ((SimpleDemo.WebAPI.Service1Soap)(this)).initAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleDemo.WebAPI.init1Response SimpleDemo.WebAPI.Service1Soap.init1(SimpleDemo.WebAPI.init1Request request) {
            return base.Channel.init1(request);
        }
        
        public string init1(string jczbh, string jcxdh, string zdlx, string ip, string mac) {
            SimpleDemo.WebAPI.init1Request inValue = new SimpleDemo.WebAPI.init1Request();
            inValue.Body = new SimpleDemo.WebAPI.init1RequestBody();
            inValue.Body.jczbh = jczbh;
            inValue.Body.jcxdh = jcxdh;
            inValue.Body.zdlx = zdlx;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            SimpleDemo.WebAPI.init1Response retVal = ((SimpleDemo.WebAPI.Service1Soap)(this)).init1(inValue);
            return retVal.Body.init1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.init1Response> SimpleDemo.WebAPI.Service1Soap.init1Async(SimpleDemo.WebAPI.init1Request request) {
            return base.Channel.init1Async(request);
        }
        
        public System.Threading.Tasks.Task<SimpleDemo.WebAPI.init1Response> init1Async(string jczbh, string jcxdh, string zdlx, string ip, string mac) {
            SimpleDemo.WebAPI.init1Request inValue = new SimpleDemo.WebAPI.init1Request();
            inValue.Body = new SimpleDemo.WebAPI.init1RequestBody();
            inValue.Body.jczbh = jczbh;
            inValue.Body.jcxdh = jcxdh;
            inValue.Body.zdlx = zdlx;
            inValue.Body.ip = ip;
            inValue.Body.mac = mac;
            return ((SimpleDemo.WebAPI.Service1Soap)(this)).init1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleDemo.WebAPI.sqsqResponse SimpleDemo.WebAPI.Service1Soap.sqsq(SimpleDemo.WebAPI.sqsqRequest request) {
            return base.Channel.sqsq(request);
        }
        
        public string sqsq(string zdlx) {
            SimpleDemo.WebAPI.sqsqRequest inValue = new SimpleDemo.WebAPI.sqsqRequest();
            inValue.Body = new SimpleDemo.WebAPI.sqsqRequestBody();
            inValue.Body.zdlx = zdlx;
            SimpleDemo.WebAPI.sqsqResponse retVal = ((SimpleDemo.WebAPI.Service1Soap)(this)).sqsq(inValue);
            return retVal.Body.sqsqResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleDemo.WebAPI.sqsqResponse> SimpleDemo.WebAPI.Service1Soap.sqsqAsync(SimpleDemo.WebAPI.sqsqRequest request) {
            return base.Channel.sqsqAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleDemo.WebAPI.sqsqResponse> sqsqAsync(string zdlx) {
            SimpleDemo.WebAPI.sqsqRequest inValue = new SimpleDemo.WebAPI.sqsqRequest();
            inValue.Body = new SimpleDemo.WebAPI.sqsqRequestBody();
            inValue.Body.zdlx = zdlx;
            return ((SimpleDemo.WebAPI.Service1Soap)(this)).sqsqAsync(inValue);
        }
    }
}
